title: "Debolina Paul"
description: "DPhil Student in Statistics, University of Oxford"
theme: minima
url: "https://debolinapaul.github.io"


author: "Debolina Paul"


# Navigation bar (for Minima theme)
minima:
  navbar:
    - title: "About"
      url: /about
    - title: "Publications"
      url: /publications
